version: '3'

services:
  wordpress:
    image: wordpress
    ports:
      - "8081:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "secret"
      WORDPRESS_DB_NAME: wordpress
    networks:
      net1:
        ipv4_address: "10.1.1.2"

  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "secret"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      net1:
        ipv4_address: "10.1.1.3"

networks:
  net1:
    ipam:
      driver: default
      config:
        - subnet: "10.1.1.0/24"